/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TareaModulo04;

import javax.swing.JOptionPane;

/**
 *
 * @author Alumno1
 */
public class RecargaAbono extends javax.swing.JFrame {

    /**
     * Creates new form RecargaAbono
     */
    public RecargaAbono() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        TextoPrincipal = new javax.swing.JLabel();
        BotonRecarga = new javax.swing.JButton();
        TextoTarjeta = new javax.swing.JLabel();
        CampoNumTarjeta = new javax.swing.JTextField();
        LogoApp = new javax.swing.JLabel();
        ImagenTarjeta01 = new javax.swing.JLabel();
        ImagenTarjeta02 = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        TextoSeleccionMes = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recarga online abono SevillaMov");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjeta01.png")).getImage());
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(620, 520));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(241, 234, 226));
        jPanel1.setPreferredSize(new java.awt.Dimension(615, 400));

        TextoPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TextoPrincipal.setText("Recarga online de su abono mensual del transporte urbano");
        TextoPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BotonRecarga.setLabel("Recargar abono");
        BotonRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRecargaActionPerformed(evt);
            }
        });

        TextoTarjeta.setText("Número de tarjeta:");

        CampoNumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumTarjetaActionPerformed(evt);
            }
        });

        LogoApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo1.png"))); // NOI18N

        ImagenTarjeta01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjetaconsorcio01.png"))); // NOI18N

        ImagenTarjeta02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjetaBus01.jpg"))); // NOI18N

        jMonthChooser1.setMonth(0);
        jMonthChooser1.setName(""); // NOI18N

        TextoSeleccionMes.setText("Seleccione el mes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(TextoPrincipal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextoTarjeta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ImagenTarjeta01)
                                        .addGap(28, 28, 28)
                                        .addComponent(ImagenTarjeta02))
                                    .addComponent(CampoNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(TextoSeleccionMes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(LogoApp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(BotonRecarga)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LogoApp)
                .addGap(22, 22, 22)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoPrincipal)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImagenTarjeta01)
                    .addComponent(ImagenTarjeta02))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextoTarjeta)
                        .addComponent(CampoNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextoSeleccionMes))
                    .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(BotonRecarga)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 57;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRecargaActionPerformed
        // Obtener el número de tarjeta del JTextField
        String numeroTarjeta = CampoNumTarjeta.getText();
        
        // Obtener el mes seleccionado del JMonthChooser
        int mesSeleccionado = jMonthChooser1.getMonth();
    
        // Convertir el número a nombre del mes
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", 
            "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        String nombreMes = meses[mesSeleccionado];
    
        // Mostrar el cuadro de diálogo con el mes seleccionado
        JOptionPane.showMessageDialog(this, "Recarga realizada para el mes de " + 
                nombreMes + " para la tarjeta número: " + numeroTarjeta);
    }//GEN-LAST:event_BotonRecargaActionPerformed

    private void CampoNumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecargaAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecargaAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecargaAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecargaAbono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecargaAbono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRecarga;
    private javax.swing.JTextField CampoNumTarjeta;
    private javax.swing.JLabel ImagenTarjeta01;
    private javax.swing.JLabel ImagenTarjeta02;
    private javax.swing.JLabel LogoApp;
    private javax.swing.JSeparator Separador;
    private javax.swing.JLabel TextoPrincipal;
    private javax.swing.JLabel TextoSeleccionMes;
    private javax.swing.JLabel TextoTarjeta;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
